# Site configuration
domain: ""
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://songroger.github.io/" # the base hostname & protocol for your site
permalink: /:title/
#avatar: http://7xof48.com1.z0.glb.clouddn.com/avatar.jpg
#about: http://7xof48.com1.z0.glb.clouddn.com/about.jpg
#favicon: http://7xof48.com1.z0.glb.clouddn.com/favicon.png
basecss: 
# Theme specific configuration
title: Coded Journey
description: >
  Hi there, My name is Luozhan.Song, usually I use "songroger" as my ID everywhere.
  I was born and raised in Hunan China. 
  I'm really fond of beautiful design, drawing etc.

# Contact and social media links
twitter_username: itsmfraser
github_username: munafraser
facebook_username: itsfraser
instagram_username: munashepics
#linkedin_username: 

exclude: ['node_modules', 'gulpfile.js', 'package.json']

kramdown:
  input: GFM

# If U enable the comment, edit disqus or duoshuo account of "/_layouts/post.html"
# before deploy your webpage
enable_comment: false

gems: ['jekyll-paginate']
# Pagination
paginate: 5
paginate_path: /archive/page:num
